services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: antonieta-frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - NUXT_HOST=0.0.0.0
  #     - NUXT_PUBLIC_API_URL=http://localhost:8000
  #   command: npm run dev
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   container_name: antonieta-backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   environment:
  #     - PYTHONPATH=/app
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=notes
  #     - POSTGRES_HOST=db
  #     - POSTGRES_PORT=5432
  #   depends_on:
  #     - db

  db:
    image: postgres:16-alpine
    container_name: antonieta-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=antonieta_usr
      - POSTGRES_PASSWORD=antonieta_passd
      - POSTGRES_DB=antonieta_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

